version: "3.8"
services:
  test-pgdb:
    container_name: test-pgdb
    image: postgres:15-alpine
    env_file:
      - .env.test
    ports:
      - "5433:5433"
    environment:
      PGPORT: 5433
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
      - "5555:5555"
    depends_on:
      - test-pgdb